base_url = "https://pranabekka.github.io"

title = "Pranab's site"

# used in index.html template as well as feed
description = """
I <3 books, programming, games with people, note-taking and UX.
"""

compile_sass = true

build_search_index = false

generate_feed = true
author = "Pranab" # used in feed

[markdown]
smart_punctuation = true
highlight_code = true
highlight_theme = "css"

[extra]
